version: '3.8'

volumes:
  mysqldata:

services:
  mysql:
    container_name: mysql
    image: mysql
    restart: on-failure
    env_file:
      - '.env.local'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: users
    volumes:
      - mysqldata:/var/lib/mysql
